apiVersion: v1
kind: Template
metadata:
  name: sources-queue-debugger
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: sources-queue-debugger
  spec:
    envName: ${ENV_NAME}
    deployments:
    - name: event-stream
      minReplicas: 1
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        env:
        - name: TOPIC
          value: platform.sources.event-stream
    - name: status
      minReplicas: 1
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        env:
        - name: TOPIC
          value: platform.sources.status
    - name: satellite-operations
      minReplicas: 1
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        env:
        - name: TOPIC
          value: platform.topological-inventory.operations-satellite
    - name: superkey-requests
      minReplicas: 1
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        env:
        - name: TOPIC
          value: platform.sources.superkey-requests
    - name: notifications
      minReplicas: 1
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        env:
        - name: TOPIC
          value: platform.notifications.ingress

    kafkaTopics:
    - topicName: platform.sources.event-stream
      partitions: 3
      replicas: 3
    - topicName: platform.sources.status
      partitions: 3
      replicas: 3
    - topicName: platform.topological-inventory.operations-satellite
      partitions: 3
      replicas: 3
    - topicName: platform.sources.superkey-requests
      partitions: 3
      replicas: 3
    - topicName: platform.notifications.ingress
      partitions: 3
      replicas: 3
    inMemoryDb: false

parameters:
- description: Image
  name: IMAGE
  value: quay.io/jlindgren/queue-debugger
- description: Image tag
  name: IMAGE_TAG
  required: true
  value: latest
- description: Clowder ENV
  name: ENV_NAME
  required: true
